# Generated by Django 5.2.7 on 2026-01-06 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ativos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('reporte_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.CharField(max_length=200)),
                ('estado_atual', models.CharField(choices=[('ABERTO', 'aberto'), ('FECHADO', 'fechado')], default='ABERTO', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='ativos.equipamentos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reportes',
                'verbose_name_plural': 'Reportes',
            },
        ),
    ]
