# Generated by Django 5.2.7 on 2025-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('auditoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(choices=[('CRIAR_EQUIPAMENTO', 'Criar equipamento'), ('ATUALIZAR_EQUIPAMENTO', 'Atualizar equipamento'), ('DELETAR_EQUIPAMENTO', 'Deletar equipamento'), ('CRIAR_SALA', 'Criar sala'), ('ATUALIZAR_SALA', 'Atualizar sala'), ('DELETAR_SALA', 'Deletar sala'), ('CRIAR_PREDIO', 'Criar predio'), ('ATUALIZAR_PREDIO', 'Atualizar predio'), ('DELETAR_PREDIO', 'Deletar predio'), ('CRIAR_SETOR', 'Criar setor'), ('ATUALIZAR_SETOR', 'Atualizar setor'), ('DELETAR_SETOR', 'Deletar setor'), ('CRIAR_AGENDAMENTO', 'Criar agendamento'), ('ATUALIZAR_AGENDAMENTO', 'Atualizar agendamento'), ('DELETAR_AGENDAMENTO', 'Deletar agendamento'), ('CRIAR_USUARIO', 'Criar usuario'), ('ATUALIZAR_USUARIO', 'Atualizar usuario'), ('DELETAR_USUARIO', 'Deletar usuario'), ('ABRIR_REPORTE', 'Abrir reporte'), ('TROCAR_EQUIPAMENTO_SALA', 'Trocar equipamento sala')], max_length=40)),
                ('alvo_id', models.IntegerField()),
                ('tipo_alvo', models.CharField(choices=[('PROJETOR', 'projetor'), ('COMPUTADOR', 'computador'), ('AR CONDICIONADO', 'ar condicionado'), ('SALA', 'sala'), ('PREDIO', 'predio'), ('SETOR', 'setor'), ('AGENDAMENTO', 'agendamento'), ('ADMINISTRADOR', 'administrador'), ('TECNICO_TI', 'tecnico de ti'), ('ALUNO', 'aluno'), ('PROFESSOR', 'professor'), ('ROOT', 'root')], max_length=40)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
            },
        ),
    ]
