# Generated by Django 5.2.7 on 2026-01-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('auditoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.TextField(choices=[('CRIAR_EQUIPAMENTO', 'Criar equipamento'), ('ATUALIZAR_EQUIPAMENTO', 'Atualizar equipamento'), ('DELETAR_EQUIPAMENTO', 'Deletar equipamento'), ('CRIAR_SALA', 'Criar sala'), ('ATUALIZAR_SALA', 'Atualizar sala'), ('DELETAR_SALA', 'Deletar sala'), ('CRIAR_PREDIO', 'Criar predio'), ('ATUALIZAR_PREDIO', 'Atualizar predio'), ('DELETAR_PREDIO', 'Deletar predio'), ('CRIAR_SETOR', 'Criar setor'), ('ATUALIZAR_SETOR', 'Atualizar setor'), ('DELETAR_SETOR', 'Deletar setor'), ('CRIAR_AGENDAMENTO', 'Criar agendamento'), ('ATUALIZAR_AGENDAMENTO', 'Atualizar agendamento'), ('DELETAR_AGENDAMENTO', 'Deletar agendamento'), ('CRIAR_USUARIO', 'Criar usuario'), ('ATUALIZAR_USUARIO', 'Atualizar usuario'), ('DELETAR_USUARIO', 'Deletar usuario'), ('ABRIR_REPORTE', 'Abrir reporte'), ('TROCAR_EQUIPAMENTO_SALA', 'Trocar equipamento sala')])),
                ('data', models.DateField(auto_now_add=True)),
                ('alvo_acao', models.TextField(choices=[('PROJETOR', 'Projetor'), ('COMPUTADOR', 'Computador'), ('AR CONDICIONADO', 'Ar condicionado'), ('SALA', 'Salas'), ('PREDIO', 'Predio'), ('SETOR', 'Setores'), ('AGENDAMENTO', 'Agendamentos'), ('ADMINISTRADOR', 'Administrador'), ('TECNICO_TI', 'Tecnico de ti'), ('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ROOT', 'Root'), ('REPORTE', 'Reportes')])),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
            },
        ),
    ]
