# Generated by Django 5.2.7 on 2026-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='alvo_acao',
            field=models.TextField(choices=[('PROJETOR', 'Projetor'), ('COMPUTADOR', 'Computador'), ('AR_CONDICIONADO', 'Ar condicionado'), ('SALA', 'Salas'), ('PREDIO', 'Predio'), ('SETOR', 'Setores'), ('AGENDAMENTO', 'Agendamentos'), ('ADMINISTRADOR', 'Administrador'), ('TECNICO_TI', 'Tecnico de ti'), ('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('REPORTE', 'Reportes')]),
        ),
    ]
