# Generated by Django 5.2.7 on 2025-11-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='tipo_alvo',
            field=models.CharField(choices=[('PROJETOR', 'Projetor'), ('COMPUTADOR', 'Computador'), ('AR CONDICIONADO', 'Ar condicionado'), ('SALA', 'Sala'), ('PREDIO', 'Predio'), ('SETOR', 'Setor'), ('AGENDAMENTO', 'Agendamento'), ('ADMINISTRADOR', 'Administrador'), ('TECNICO_TI', 'Tecnico de ti'), ('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('ROOT', 'Root'), ('REPORTE', 'Reporte')], max_length=40),
        ),
    ]
