# Generated by Django 5.2.7 on 2026-01-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_alter_auditorialog_alvo_acao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorialog',
            name='acao',
            field=models.TextField(choices=[('CRIAR_EQUIPAMENTO', 'Criar equipamento'), ('CRIAR_SALA', 'Criar sala'), ('CRIAR_PREDIO', 'Criar predio'), ('CRIAR_SETOR', 'Criar setor'), ('CRIAR_AGENDAMENTO', 'Criar agendamento'), ('CRIAR_USUARIO', 'Criar usuario'), ('ATUALIZAR_EQUIPAMENTO', 'Atualizar equipamento'), ('ATUALIZAR_SALA', 'Atualizar sala'), ('ATUALIZAR_PREDIO', 'Atualizar predio'), ('ATUALIZAR_SETOR', 'Atualizar setor'), ('ATUALIZAR_AGENDAMENTO', 'Atualizar agendamento'), ('ATUALIZAR_USUARIO', 'Atualizar usuario'), ('DELETAR_EQUIPAMENTO', 'Deletar equipamento'), ('DELETAR_SALA', 'Deletar sala'), ('DELETAR_PREDIO', 'Deletar predio'), ('DELETAR_SETOR', 'Deletar setor'), ('DELETAR_AGENDAMENTO', 'Deletar agendamento'), ('DELETAR_USUARIO', 'Deletar usuario'), ('ABRIR_REPORTE', 'Abrir reporte'), ('TROCAR_EQUIPAMENTO_SALA', 'Trocar equipamento sala')]),
        ),
    ]
