services:
  galt-database:
      image: postgres:17
      container_name: "galt-database"
      env_file:
        - ./env/galtDatabase.env
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
        interval: 2s
        timeout: 5s
        retries: 2
      ports:
        - "5432:5432"
      volumes:
        - "galtDatabase:/var/lib/postgresql/data"

  galt-redis:
    image: redis:8.4.0
    container_name: "galt-redis"
    ports:
      - "6379:6379"

  galt-service:
    build: .
    container_name: "galt-service"
    env_file:
      ./env/galtService.env
    depends_on:
      galt-database:
        condition: service_healthy

    expose:
      - "8000"
    volumes:
      - staticfiles:/app/staticfiles
volumes:
  galtDatabase:
  staticfiles:
