services:
  galt-database:
      image: postgres:17
      container_name: "galt-database"
      env_file:
        - ./env/galtDatabase.env
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
        interval: 2s
        timeout: 5s
        retries: 2
      ports:
        - "5432:5432"
      volumes:
        - "galtDatabase:/var/lib/postgresql/data"

  galt-service:
      build: .
      container_name: "galt-service"
      env_file:
        ./env/galtService.env
      depends_on:
        galt-database:
          condition: service_healthy
      entrypoint: [ "/bin/sh", "-c" ]
      command: >
          "python manage.py migrate --noinput &&
           python manage.py createsuperuser --noinput || true &&
           python manage.py runserver 0.0.0.0:8000"
      ports:
        - "8000:8000"
volumes:
  galtDatabase:
