# Generated by Django 5.2.7 on 2026-01-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predios',
            fields=[
                ('predio_id', models.AutoField(primary_key=True, serialize=False)),
                ('predio', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
            },
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('setor_id', models.AutoField(primary_key=True, serialize=False)),
                ('setor', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100, null=True)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='locais.predios')),
            ],
            options={
                'verbose_name': 'Setores',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_atual', models.CharField(choices=[('LIBERADA', 'Liberada'), ('MANUTENCAO', 'Manutenção'), ('FECHADA', 'Fechada')], default='LIBERADA', max_length=50)),
                ('localizacao', models.CharField(max_length=50)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='locais.setores')),
            ],
            options={
                'verbose_name': 'Salas',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
