# Generated by Django 5.2.7 on 2025-10-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('predio_id', models.AutoField(primary_key=True, serialize=False)),
                ('predio', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('setor_id', models.AutoField(primary_key=True, serialize=False)),
                ('setor', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.CreateModel(
            name='PredioSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predios_setores', to='locais.predio')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predios_setores', to='locais.setor')),
            ],
            options={
                'verbose_name': 'Predio e setor',
                'verbose_name_plural': 'Predios e setors',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('estado_sala', models.CharField(choices=[('LIBERADA', 'Liberada'), ('MANUTENCAO', 'Manutencao'), ('INAPTA', 'Inapta')], default='LIBERADA', max_length=40)),
                ('localizacao', models.CharField(max_length=6)),
                ('predio_setor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='salas', to='locais.prediosetor')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'constraints': [models.UniqueConstraint(fields=('predio_setor', 'numero'), name='u_predio_numero')],
            },
        ),
        migrations.AddConstraint(
            model_name='prediosetor',
            constraint=models.UniqueConstraint(fields=('predio', 'setor'), name='u_predio_setor'),
        ),
    ]
