# Generated by Django 5.2.7 on 2025-10-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='predio_setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='locais.prediosetor'),
        ),
    ]
