# Generated by Django 5.2.7 on 2025-12-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_alter_sala_predio_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='localizacao',
            field=models.CharField(max_length=20),
        ),
    ]
