# Generated by Django 5.2.7 on 2025-12-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0003_alter_sala_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='estado_sala',
            field=models.CharField(choices=[('LIBERADA', 'Liberada'), ('MANUTENCAO', 'Manutencao'), ('FECHADA', 'Fechada')], default='LIBERADA', max_length=40),
        ),
    ]
