# Generated by Django 5.2.7 on 2026-01-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0004_alter_sala_estado_sala'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediosetor',
            options={'ordering': ['predio__predio', 'setor__setor'], 'verbose_name': 'Predio e setor', 'verbose_name_plural': 'Predios e setors'},
        ),
        migrations.AlterField(
            model_name='predio',
            name='predio',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='estado_sala',
            field=models.CharField(choices=[('LIBERADA', 'Liberada'), ('MANUTENCAO', 'Manutenção'), ('FECHADA', 'Fechada')], default='LIBERADA'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='localizacao',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sala',
            name='numero',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='setor',
            name='setor',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
