# Generated by Django 5.2.7 on 2025-11-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno'), ('TECNICO_TI', 'Tecnico de TI'), ('ADMINISTRADOR', 'Administrador'), ('ROOT', 'Root')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
