# Generated by Django 5.2.7 on 2026-01-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='email_pessoal',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='telefone',
        ),
    ]
