# Generated by Django 5.2.7 on 2026-01-07 01:36
import uuid

from django.db import migrations

from core.essenciais import TipoUsuario
def retornar_tipos_usuarios() -> list[TipoUsuario]:
    return  [
        TipoUsuario.TECNICO_TI,
        TipoUsuario.ADMINISTRADOR,
        TipoUsuario.SERVIDOR,
        TipoUsuario.ALUNO
    ]

def criar_tipos_usuarios(apps, schema_editor):
    Groups_model= apps.get_model('auth', 'Group')
    grupos_usuarios = retornar_tipos_usuarios()

    for tipo_usuario in grupos_usuarios:
        Groups_model.objects.get_or_create(name=tipo_usuario.name)


def remover_tipos_usuarios(apps, schema_editor):
    Groups_model= apps.get_model('auth', 'Group')
    grupos_usuarios = retornar_tipos_usuarios()

    for tipo_usuario in grupos_usuarios:
        Groups_model.objects.remove(name=tipo_usuario.name)

class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_tipos_usuarios, remover_tipos_usuarios)
    ]
