# Generated by Django 5.2.7 on 2026-01-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='padrao', max_length=20),
            preserve_default=False,
        ),
    ]
