# Generated by Django 5.2.7 on 2026-01-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_insert_tipos_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='email_pessoal',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email_escolar',
            field=models.EmailField(max_length=100),
        ),
    ]
