# Generated by Django 5.2.7 on 2026-01-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_usuario_senha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
