# Generated by Django 5.2.7 on 2026-01-08 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_remove_usuarios_email_pessoal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nome',
        ),
    ]
