# Generated by Django 5.2.7 on 2026-01-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_remove_usuarios_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(default='usuario', max_length=100),
            preserve_default=False,
        ),
    ]
