# Generated by Django 5.2.7 on 2026-01-12 17:17

from django.db import migrations
from django.contrib.auth.hashers import make_password

def criar_usuarios(apps, schema_editor):
    Usuario_model = apps.get_model('contas', 'Usuarios')
    Tecnico_model = apps.get_model('contas', 'TecnicosTI')
    Groups_model = apps.get_model('auth', 'Group')

    group_admin = Groups_model.objects.get(name='ADMINISTRADOR')
    group_tecnico = Groups_model.objects.get(name='TECNICO_TI')
    group_aluno = Groups_model.objects.get(name='ALUNO')
    group_servidor = Groups_model.objects.get(name='SERVIDOR')

    admin, created_admin = Usuario_model.objects.get_or_create(
        username='admin@escolar.com',
        defaults={
            'nome': 'Administrador',
            'email': 'admin@gmail.com',
            'email_escolar': 'admin@escolar.com',
            'cpf': '000.000.000-00',
            'numero': '00000000000',
            'is_staff': True,
            'is_superuser': True
        }
    )

    if created_admin:
        admin.password = make_password('senha')
        admin.save()
        admin.groups.add(group_admin)
        admin.groups.add(group_tecnico)
        admin.groups.add(group_aluno)
        admin.groups.add(group_servidor)

    aluno, created_aluno = Usuario_model.objects.get_or_create(
        username='aluno@escolar.com',
        defaults={
            'nome': 'aluno',
            'email': 'aluno@gmail.com',
            'email_escolar': 'aluno@escolar.com',
            'cpf': '000.000.000-01',
            'numero': '00000000001',
            'is_staff': False,
            'is_superuser': False
        }
    )

    if created_aluno:
        aluno.password = make_password('senha')
        aluno.save()
        aluno.groups.add(group_aluno)

    tecnico_ti, created_tecnico = Usuario_model.objects.get_or_create(
        username='tecnico@escolar.com',
        defaults={
            'nome': 'tecnico',
            'email': 'tecnico@gmail.com',
            'email_escolar': 'tecnico@escolar.com',
            'cpf': '000.000.000-02',
            'numero': '00000000002',
            'is_staff': False,
            'is_superuser': False
        }
    )

    if created_tecnico:
        tecnico_ti.password = make_password('senha')
        tecnico_ti.save()
        tecnico_ti.groups.add(group_tecnico)
        Tecnico_model.objects.get_or_create(usuario=tecnico_ti, cargo= 'Auxiliar')

    servidor, created_servidor = Usuario_model.objects.get_or_create(
        username='servidor@escolar.com',
        defaults={
            'nome': 'servidor',
            'email': 'servidor@gmail.com',
            'email_escolar': 'servidor@escolar.com',
            'cpf': '000.000.000-03',
            'numero': '00000000003',
            'is_staff': False,
            'is_superuser': False
        }
    )

    if created_servidor:
        servidor.password = make_password('senha')
        servidor.save()
        servidor.groups.add(group_servidor)

def remover_usuario(apps, schema_editor):
    Usuario_model = apps.get_model('contas', 'Usuarios')

    for usuario in Usuario_model.objects.all():
        if usuario.username == 'admin@escolar.com' or usuario.username == 'tecnico@escolar.com' or usuario.username == 'aluno@escolar.com' or usuario.username == 'servidor@escolar.com':
            usuario.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_usuarios_nome'),
    ]

    operations = [
        migrations.RunPython(criar_usuarios, remover_usuario)
    ]
