# Generated by Django 5.2.7 on 2026-01-07 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('agendamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('data', models.DateField()),
                ('estado_atual', models.CharField(choices=[('A_SER_REALIZADO', 'A ser realizado'), ('FAZENDO', 'Fazendo'), ('ESPERANDO_CONFIRMACAO', 'Esperando confirmação'), ('INACABADO', 'Inacabado'), ('FEITO', 'Feito')], default='A_SER_REALIZADO', max_length=100)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='locais.salas')),
            ],
            options={
                'verbose_name': 'Agendamentos',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='TecnicosTIAgendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_tecnicos', to='agendas.agendamentos')),
            ],
            options={
                'verbose_name': 'TecnicosTI e Agendamentos',
                'verbose_name_plural': 'TécnicosTI e agendamentos',
            },
        ),
    ]
