# Generated by Django 5.2.7 on 2025-10-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendas', '0001_initial'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicotiagendamento',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_tecnicos', to='contas.tecnicoti'),
        ),
    ]
