# Generated by Django 5.2.7 on 2026-01-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicostiagendamentos',
            name='responsavel',
            field=models.BooleanField(default=True),
        ),
    ]
