# Generated by Django 5.2.7 on 2025-10-24 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0002_initial'),
        ('locais', '0002_alter_sala_predio_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='locais.sala'),
        ),
    ]
