# Generated by Django 5.2.7 on 2026-01-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendas', '0003_tecnicostiagendamentos_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
