# Generated by Django 5.2.7 on 2026-01-06 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('equipamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('posicao', models.IntegerField()),
                ('tipo', models.TextField(choices=[('PROJETOR', 'Projetor'), ('COMPUTADOR', 'Computador'), ('AR_CONDICIONADO', 'Ar condicionado')])),
                ('serial', models.IntegerField(unique=True)),
                ('estado_atual', models.CharField(choices=[('FUNCIONANDO', 'Funcionando'), ('MANUTENCAO', 'Manutencao'), ('DEFEITUOSO', 'Defeituoso')], default='FUNCIONANDO', max_length=50)),
                ('fabricante', models.CharField(max_length=100)),
                ('data_aquisicao', models.DateField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='locais.salas')),
            ],
            options={
                'verbose_name': 'Equipamentos',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoManutencoes',
            fields=[
                ('historico_manutencoes_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('equipamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencoes', to='ativos.equipamentos')),
            ],
            options={
                'verbose_name': 'Historico de Manutencoes',
                'verbose_name_plural': 'Historicos de Manutencoes',
            },
        ),
        migrations.AddConstraint(
            model_name='equipamentos',
            constraint=models.UniqueConstraint(fields=('posicao', 'sala'), name='u_posicao_sala'),
        ),
    ]
