# Generated by Django 5.2.7 on 2025-10-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('equipamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PROJETOR', 'Projetor'), ('COMPUTADOR', 'Computador'), ('AR_CONDICIONADO', 'Ar condicionado')], max_length=40)),
                ('serial', models.IntegerField(unique=True)),
                ('posicao', models.CharField(max_length=6)),
                ('estado_equipamento', models.CharField(choices=[('FUNCIONANDO', 'Funcionando'), ('MANUTENCAO', 'Manutencao'), ('DEFEITUOSO', 'Defeituoso')], default='FUNCIONANDO', max_length=40)),
                ('manutencoes', models.IntegerField(default=0)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='equipamentos', to='locais.sala')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='HistoricoManutencoes',
            fields=[
                ('historico_manutencoes_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencoes', to='ativos.equipamento')),
            ],
            options={
                'verbose_name': 'Historico de Manutencoes',
                'verbose_name_plural': 'Historicos de Manutencoes',
            },
        ),
        migrations.AddConstraint(
            model_name='equipamento',
            constraint=models.UniqueConstraint(fields=('posicao', 'sala'), name='u_posicao_sala'),
        ),
    ]
