# Generated by Django 5.2.7 on 2026-01-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='data_aquisicao',
            field=models.DateField(),
        ),
    ]
