# Generated by Django 5.2.7 on 2026-01-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_alter_equipamentos_data_aquisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='serial',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
