# Generated by Django 5.2.7 on 2025-11-17 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0002_alter_equipamento_sala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomanutencoes',
            name='equipamento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencoes', to='ativos.equipamento'),
        ),
    ]
