# Generated by Django 5.2.7 on 2025-12-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_alter_historicomanutencoes_equipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='posicao',
            field=models.CharField(max_length=20),
        ),
    ]
