# Generated by Django 5.2.7 on 2026-01-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0003_alter_equipamentos_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomanutencoes',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencoes', to='ativos.equipamentos'),
        ),
    ]
