# Generated by Django 5.2.7 on 2026-01-19 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_alter_historicomanutencoes_equipamento'),
        ('contas', '0006_criar_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomanutencoes',
            name='tecnico',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencoes', to='contas.tecnicosti'),
            preserve_default=False,
        ),
    ]
