# Generated by Django 5.2.7 on 2025-12-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0004_alter_equipamento_posicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.CharField(default='padrao', max_length=40),
            preserve_default=False,
        ),
    ]
