# Generated by Django 5.2.7 on 2026-01-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_historicomanutencoes_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentos',
            name='fileira',
            field=models.CharField(choices=[('Fileira de computadores a esquerda', 'Fileira Computadores Esquerda'), ('Fileira de computadores a direita', 'Fileira Computadores Direita'), ('Fundo', 'Fundo')], default='FILEIRA_COMPUTADORES_DIREITA', max_length=50),
            preserve_default=False,
        ),
    ]
