# Generated by Django 5.2.7 on 2026-01-22 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0005_historicomanutencoes_tecnico'),
        ('contas', '0006_criar_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomanutencoes',
            name='tecnico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencoes', to='contas.tecnicosti'),
        ),
    ]
