# Generated by Django 5.2.7 on 2026-01-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0006_equipamentos_fileira'),
        ('locais', '0002_alter_setores_localizacao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipamentos',
            name='u_posicao_sala',
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='fileira',
            field=models.CharField(choices=[('FILEIRA_COMPUTADORES_ESQUERDA', 'Fileira de computadores a esquerda'), ('FILEIRA_COMPUTADORES_DIREITA', 'Fileira de computadores a direita'), ('FUNDO', 'Fundo')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='equipamentos',
            constraint=models.UniqueConstraint(fields=('posicao', 'fileira'), name='u_posicao_fileira'),
        ),
    ]
