# Generated by Django 5.2.7 on 2026-01-23 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0007_alter_historicomanutencoes_tecnico'),
        ('ativos', '0007_remove_equipamentos_u_posicao_sala_and_more'),
    ]

    operations = [
    ]
