# Generated by Django 5.2.7 on 2026-01-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0008_merge_20260122_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='estado_atual',
            field=models.CharField(choices=[('FUNCIONANDO', 'Funcionando'), ('MANUTENCAO', 'Manutencao'), ('DEFEITUOSO', 'Defeituoso'), ('ALERTA', 'Alerta')], default='FUNCIONANDO', max_length=50),
        ),
    ]
