# Generated by Django 5.2.7 on 2026-01-26 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0009_alter_equipamentos_estado_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicomanutencoes',
            name='titulo',
            field=models.TextField(max_length=100),
        ),
    ]
