# Generated by Django 5.2.7 on 2026-01-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0010_alter_historicomanutencoes_titulo'),
        ('locais', '0002_alter_setores_localizacao'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipamentos',
            name='u_posicao_fileira',
        ),
        migrations.AddConstraint(
            model_name='equipamentos',
            constraint=models.UniqueConstraint(fields=('posicao', 'fileira', 'sala'), name='u_posicao_fileira_sala'),
        ),
    ]
