# Generated by Django 5.2.7 on 2026-01-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0011_remove_equipamentos_u_posicao_fileira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentos',
            name='serial',
            field=models.CharField(max_length=13),
        ),
    ]
